### PR TITLE
Add support for client-side template rendering

### PR DESCRIPTION
**Pull request by eduardoboucas**
# Overview

This PR introduces the ability for Dust templates (both pages and partials), to be rendered on the client, as well as on the server. This feature came about as a requirement for Publish, but I think it would be a great addition to Web.

Transforming a Dust template into HTML happens in two phases: compiling, where a template is converted into a JavaScript function, and rendering, where that function returns a string of HTML based on the arguments it received. Both phases can happen on the server and on the client (see [*Compiling and Rendering*](http://www.dustjs.com/guides/rendering/)).

When rendering on the client, it's preferable to compile on the server, as that removes a good part of the heavy-lifting from the client and the Dust client-side library required is lighter (`dust-core` instead of `dust-full`). With Web, we're already compiling all the templates on the server anyway, so we just need to make them available to the client by writing them to a publicly-available location.

# Usage

A new setting was added to the config, with three sub-settings.

- `clientRender`
  - `enabled`: Whether templates are to be made available to the client
  - `outputFormat`: Whether all templates will be merged into a single JS file (`combined`), or each template will be on its own file (`separate`)
  - `outputPath`: The path to where the template files should be written, relative to the public folder. This should be a folder when `outputFormat` is `separate` and a file when `combined`

# Example

Let's imagine a site containing two templates: `index.dust` and `article.dust`.

```html
<!-- index.dust -->
<h1>Latest news:</h1>

{#articles}
    {> "partials/article"}
{/articles}
```

```html
<!-- article.dust -->
<article class="news">
	<h2 class="news__title">{title}</h2>
	<p class="news__body">{body}</p>
</article>
```

The initial load will happen entirely on the server, but we can subsequently append new articles to the page, dynamically and re-using the same templates.

Each template will be made available with the same name as on the server, as the screenshot below shows.

screen shot 2016-04-08 at 12 37 43

Let me know your thoughts @josephdenne @jimlambie @mingard.

(Tests to follow if we go ahead with this)

### CODE REVIEW

**Comment by mingard** [comment]
@eduardoboucas this is fantastic

**Comment by josephdenne** [comment]
Can you document the requirement for Publish for prosperity please?

**Comment by eduardoboucas** [comment]
Sure. I'll work with @mingard on getting it detailed in the brief.

**Comment by abovebored** [comment]
This seems like it fits well with the isomorphic model – http://nerds.airbnb.com/isomorphic-javascript-future-web-apps/

**Comment by abovebored** [comment]
:tophat: @magnus

**Comment by abovebored** [comment]
:tophat: @mdahlstrand

**Comment by josephdenne** [comment]
"Isomorphic JavaScript" - nice spot @abovebored

**Comment by eduardoboucas** [comment]
That's precisely the idea. We get the initial state from the server and then add to it on the client, whilst reusing the same templating logic and therefore not doing things like writing HTML in a JavaScript file (yikes!).

Similar in principle to what people are doing with React and others.

**Comment by mdahlstrand** [comment]
Nice feature @eduardoboucas, will pull and review. Maybe squash the commits before merging?

And great link @abovebored 👍 Leads me on to this:
Have there been any conversations on how to best make the app run on both the client and the server? This is something I see as quite necessary to fully make use of this feature without forcing developers to write everything twice.

**Comment by eduardoboucas** [comment]
Not sure I understand your question @mdahlstrand. What other parts of the app do you see running on the client, and what would developers still need to write twice now that templates (and helpers, if we want) can be shared?

**Comment by josephdenne** [comment]
@mdahlstrand: there's currently no plan to support the app running in browser for a number of reasons, including security. What's your thinking on this front?

Re: squashing commits, we generally prefer them open and visible in PRs, as it gives clarity of process, which is often useful for gaining a full understanding of the work

**Comment by mdahlstrand** [comment]
@josephdenne & @eduardoboucas 
Re squashing: Thought the two "remove debug code" commits in there which only make tiny changes could be squashed into the main commit, as it'd show more clearly what is going on.

Re what to run on the client:
As I see it, rendering templates on the client only become really useful when routing and a data model (fetching/syncing) also are able to run on the client, as it would enable the client to be fully "ajax". If we can only render templates (but not query the api or know which page/template hierarchy to render when presented a uri), I don't see how client rendering is very useful apart from the very simplest of cases which don't depend on external data - we still have to query the server for the routing and data, so we might as well have the server render the page/component too.

I believe the confusion comes from me imagining dadi/web making it easy to write websites that work more like "webapps", where we don't have to do a whole page load when links are clicked, whereas I guess this PR is aimed at more "widget/component-like" (date pickers, etc) implementations?

**Comment by eduardoboucas** [comment]
@mdahlstrand I disagree that rendering on the client is useful only when fetching external data. There are a lot of situations where you want to change the state of the interface based purely on user interaction (e.g. error messages, notifications, a document builder in a CMS interface where each component the user can add to an article is a separate partial). Being able to re-use these templates on the server and client alone seems like a huge benefit to me.

Also, there's nothing stopping you from building that "fully ajax" application you described. Say that you want to create a form that inserts a document in the API and you don't want to trigger a page reload when the user submits it. I believe the best approach to this is to hijack the form submission if the client meets certain conditions (using a "cut the mustard" approach in the name of progressive enhancement et al.), send an Ajax request instead and based on the results[1] do something to the UI — and this *something* is made possible by the client-side Dust rendering proposed in this PR.

[1] This part of the process would be easier and cleaner if your Ajax request could return just a JSON object with the result of the operation and some additional data necessary, instead of a full HTML page that you'd need to parse, which you can do in the logic of your template (e.g. if the request is asking for JSON, print *this*, otherwise print the whole HTML block).

We could look into whether it would make sense to bake this last step into Web, but in my opinion that's as far as we should go. I don't see how a Web server — which should be agnostic of client-side implementations — could help you any further in developing what you're after.

**Comment by mdahlstrand** [comment]
@eduardoboucas Ok, understand your viewpoint!

**Comment by mdahlstrand** [comment]
Just thinking a little more about this @eduardoboucas - would it make sense to use the same form/data validation on the server side and the client side, making the showing of error messages independent (but identical in behaviour) of the server?

**Comment by eduardoboucas** [comment]
By making a page/route able to return a JSON object in alternative to HTML, you could do the validation on the server and return any error messages that result from the operation as part of the response, which you'd then pass to the client-side template to be displayed. That's one way of doing it without any code duplication.

Ultimately, it would depend on what the interface requires. For example, if you want to validate a field as the user types, it wouldn't be practical to make a round-trip to the server on every keystroke. In that case, you'd probably want to use some client-side validation logic and render just the error message when appropriate (which could itself be a client-side rendered template).

**Comment by jimlambie** [comment]
@eduardoboucas please push to this branch again to kick the CI tests off? It got beached somewhere along the way...

**Comment by eduardoboucas** [comment]
@jimlambie Sure thing. I want to make some changes to the helpers file anyway, so they can be made available to the client-side as well. I should have a commit ready sometime today.

**Comment by eduardoboucas** [comment]
Hello again folks! So, the next logical step to this PR was to make helpers and filters available to the client as well as the templates, because if you are rendering them on the browser, chances are you'll need to use helpers too. 

To implement this, I took some time to look into which and how helpers are handled in Web, and I ended up changing some things, to better support not only this particular feature but also the long-term vision of the product (e.g. the option to support other templating engines).

### The current state of helpers

Currently, the following helpers are being loaded by the application:

1. [dustjs-helpers](https://github.com/linkedin/dustjs-helpers): the official core Dust helpers pack;
2. [common-dustjs-helpers](https://github.com/rodw/common-dustjs-helpers): a community-maintained helpers pack;
3. [our own set of helpers](https://github.com/dadi/web/blob/master/dadi/lib/dust/helpers.js): a list of miscellaneous helpers which one or more of our client projects required at some point in time.
4. Any files placed in the helpers directory inside the workspace (`app/utils/helpers` by default).

Items 1 to 3 are loaded at app start, and reloaded when a file changes. Item 4 is loaded on view generation. The fact that helpers are loaded at different times in the app lifecycle made it difficult to make them available to the client.

### Change 1: Move all interactions with Dust.js to a separate class

Currently, the Dust.js engine is being accessed from multiple places in the codebase, to add helpers/filters or to render and compile templates. I propose that all these interactions are decoupled from the server logic and moved to a new `Dust` class, that encapsulates and centralises all interactions with Dust.js. 

This class exposes methods for things like loading all helpers on a directory or compiling all templates from a list of files, making it easier to keep track of when exactly things are being loaded and pass data to the client accordingly. It will be the only module in the codebase requiring the `dustjs-linkedin` module and holding a reference to it.

This also makes the task of supporting alternative templating engines a lot easier, since the core server logic becomes pretty much agnostic of templating engine.

### Change 2: Remove non-core helpers from the codebase

I don't think *Web* should be shipping with any helpers apart from the core pack maintained by the Dust.js team. 

[Our list of helpers](https://github.com/dadi/web/blob/master/dadi/lib/dust/helpers.js) include solutions that are right and useful for us in certain projects, but we shouldn't make that decision for other people using the platform. Also, by shipping with them we are commiting to not only maintain them in the long term, but also document their functionality.
   
I propose that we move all those helpers (and their respective unit tests) to a separate codebase, which any project can include as a npm dependency if they need the functionality. On a first phase, we could include this package as a dependency by default to avoid a breaking change, and remove it once we do the next major version bump.
   
I prepared [a temporary repository](https://github.com/eduardoboucas/dadi-dustjs-helpershttps://github.com/eduardoboucas/dadi-dustjs-helpers) for this, which still needs the test suite added and some love in general.

### The new state of helpers

The core `dustjs-helpers` package is loaded automatically by the new `Dust` class. Any other helpers are loaded from files placed in the helpers directory (`app/utils/helpers`), either by having the code for the helpers directly in the file or by calling another module using `require()`.

To include all the third-party helpers we currently ship with, we could do the following:

```js
/* app/utils/helpers/loader.js */

// Reference to the Dust class
var dust = require(__dirname + '/../../../dust');

// Load DADI helpers
require('dadi-dustjs-helpers')(dust.getEngine());

// Load common-dustjs-helpers (https://github.com/rodw/common-dustjs-helpers)
var commonDustHelpers = require('common-dustjs-helpers');
new commonDustHelpers.CommonDustjsHelpers().export_helpers_to(dust.getEngine());

// Any other helpers package...
```
    
### Finally back on topic, client-side templates

With the new `Dust` class in place, it's now easier to make whatever data we want available to the client. The new `dust.clientRender` config object has the following properties:

- `enabled`: If true, compiled templates are made available to the client-side
- `templates`
  - `format`: Defines whether compiled templates are written to individual JS files (`separate`) or combined into a single one (`combined`)
  - `path`: The location where compiled templates should be written to, relative to `public`. This should be a folder when `format` is `separate` and a file when `combined`
- `helpers`
  - `path`: The location where helpers should be written to. If empty, helpers will not be included.
- `filters`
  - `path`: The location where filters should be written to. If empty, filters will not be included.

It is possible to combine any of the 3 items (templates, helpers and filter) into a single file. To do this, one would set all `path` fields to the same value and `templates.format` to `combine`.

---

Looking forward to hearing your thoughts on this. I've been sharing templates and helpers between server and client on oolipo, and it works quite well. I can't post a link here as the product is in closed beta at the moment, but please do ping me if you're interested in having a look.

@jimlambie I removed the tests for our helpers, as they would then live on their own package. If you're happy with how these changes look, I can look into possibly adding some more tests specific to the `Dust` class.

Thank you! 👋

**Comment by jimlambie** [comment]
Amazing stuff. Please go ahead with any tests you need to add and let me
know if I can help with the helpers package publishing

**Comment by eduardoboucas** [comment]
(Sorry I'm taking a while on this. There are still a couple of rough edges I want to address, and I'm using the experience from oolipo and more recently Publish to perfect the process.)

**Comment by jimlambie** [comment]
(it's ok, 沒關係）

**Comment by eduardoboucas** [comment]
Finally had the chance to look into this again. Few things to note:

- I removed support for writing helpers and filters to the client, because unfortunately Dust.js doesn't offer a reliable way of doing this. We will leave it up to developers to package and include any helpers/filters they might require on the client-side.

- Added a `whitelist` option to the config, as an array of strings. When enabled, only templates whose name matches one of the entries in this array will be made available to the client. It supports wildcards.

     *Example: Only templates with names starting with `partials/` will be made available to the client-side*
     ```json
"dust": {
      "clientRender": {
        "enabled": true,
        "format": "combined",
        "path": "templates.js",
        "whitelist": [
          "partials/*"
        ]
      }
}
    ```

- As mentioned above, this PR decouples all interactions with Dust.js to pave way for supporting other templating languages in the future. As part of that, all Dust.js helpers were removed from the codebase and moved to this [temporary repository](https://github.com/eduardoboucas/dadi-dustjs-helpers). The repository now contains a full testing suite for all the helpers. I believe it's ready to be moved to a DADI repository and published to npm. Once that's done, this PR is ready to merge.

**Comment by eduardoboucas** [comment]
As requested by @jimlambie, added advanced caching option to templates:

- if `config.dust.cache` is set to `true`, partials will ​**always**​ be cached;
- added a `config.dust.cachePages` (defaults to `true`), that allows caching to be disabled for pages (so only partials will be cached);
- alternatively to disabling cache for all pages, it can still be done on a per-page basis by setting `settings.cache` to `false` in the page JSON schema

**Pull request merged**
