### PR TITLE
Disable API by default

### PR DESCRIPTION
**Pull request by abovebored**
I propose disabling the API configuration block by default. First time users who are interested in exploring Web's features experience an error on first load related to an API not being present at the location specified in the `config.json`. This way you can also keep the config file cleaner by removing the `api` block all together if you don't need it.

Users who are actively connecting Web to API will have less ambiguity by having to explicitly set `"enabled": true`.

Additionally includes an update of the message in the console to indicate when `config.api.enabled === false` to say `Disabled` rather than `Not found`. It's confused me a few times as to what exactly was happening as it suggests it is _looking_ for the API but not finding it (404 or 401 error) rather than it not even trying.

### CODE REVIEW

**Comment by eduardoboucas** [comment]
Isn't this the same as #109?

**Comment by abovebored** [comment]
Ah yes it is @eduardoboucas. I made this because of #110 - it feels to me like this makes more sense now.

**Comment by adamkdean** [comment]
I agree with this. It is a breaking change, sure, but we should be able to take web and use it without bolting anything else on. A great example is the markdown provider which allows us to use web for a static site without any backing services. 💯

**Comment by eduardoboucas** [comment]
Like I said on #109, I have nothing against this, as long as we flag it as a breaking change and therefore bump a major version.

**Comment by adamkdean** [comment]
Definitely. 

Do we have any other substantial changes that could go in at the same time?

**Comment by jimlambie** [comment]
There's a few yeah. I'll roll out a new branch tomorrow that will form the basis of the next release. Will remove semantic release for this product.

**Comment by jimlambie** [comment]
Anyone having a go at tests for the markdown provider?

**Comment by abovebored** [comment]
I will happily 🙋, unless @adamkdean has a overwhelming desire?

**Comment by jimlambie** [comment]
Can't  be much different to the Static provider https://github.com/dadi/web/blob/master/test/unit/data-providers.js#L177

**Comment by adamkdean** [comment]
No overwhelming desire here. It's all yours, @abovebored 🏹 🎯

**Comment by abovebored** [comment]
url

**Pull request merged**
